var global=this,channelId=Math.floor(1E4*Math.random()),emptyFn=Function.prototype,reURI=/^((http.?:)\/\/([^:\/\s]+)(:\d+)*)/,reParent=/[\-\w]+\/\.\.\//,reDoubleSlash=/([^:])\/\//g,namespace="",easyXDM={},_easyXDM=window.easyXDM,IFRAME_PREFIX="easyXDM_",HAS_NAME_PROPERTY_BUG,useHash=!1,flashVersion,HAS_FLASH_THROTTLED_BUG,_trace=emptyFn;function isHostMethod(a,b){var c=typeof a[b];return"function"==c||!!("object"==c&&a[b])||"unknown"==c}
function isHostObject(a,b){return!!("object"==typeof a[b]&&a[b])}function isArray(a){return"[object Array]"===Object.prototype.toString.call(a)}
function hasFlash(){if(!undef(navigator.plugins)&&"object"==typeof navigator.plugins["Shockwave Flash"]){var a=navigator.plugins["Shockwave Flash"].description;a&&!undef(navigator.mimeTypes)&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(flashVersion=a.match(/\d+/g))}if(!flashVersion){var b;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),flashVersion=Array.prototype.slice.call(b.GetVariable("$version").match(/(\d+),(\d+),(\d+),(\d+)/),
1)}catch(c){}}if(!flashVersion)return!1;a=parseInt(flashVersion[0],10);b=parseInt(flashVersion[1],10);HAS_FLASH_THROTTLED_BUG=9<a&&0<b;return!0}var on,un;
if(isHostMethod(window,"addEventListener"))on=function(a,b,c){_trace("adding listener "+b);a.addEventListener(b,c,!1)},un=function(a,b,c){_trace("removing listener "+b);a.removeEventListener(b,c,!1)};else if(isHostMethod(window,"attachEvent"))on=function(a,b,c){_trace("adding listener "+b);a.attachEvent("on"+b,c)},un=function(a,b,c){_trace("removing listener "+b);a.detachEvent("on"+b,c)};else throw Error("Browser not supported");var domIsReady=!1,domReadyQueue=[],readyState;
"readyState"in document?(readyState=document.readyState,domIsReady="complete"==readyState||~navigator.userAgent.indexOf("AppleWebKit/")&&("loaded"==readyState||"interactive"==readyState)):domIsReady=!!document.body;function dom_onReady(){if(!domIsReady){domIsReady=true;_trace("firing dom_onReady");for(var a=0;a<domReadyQueue.length;a++)domReadyQueue[a]();domReadyQueue.length=0}}
if(!domIsReady){if(isHostMethod(window,"addEventListener"))on(document,"DOMContentLoaded",dom_onReady);else if(on(document,"readystatechange",function(){document.readyState=="complete"&&dom_onReady()}),document.documentElement.doScroll&&window===top){var doScrollCheck=function(){if(!domIsReady){try{document.documentElement.doScroll("left")}catch(a){setTimeout(doScrollCheck,1);return}dom_onReady()}};doScrollCheck()}on(window,"load",dom_onReady)}
function whenReady(a,b){domIsReady?a.call(b):domReadyQueue.push(function(){a.call(b)})}function getParentObject(){var a=parent;if(namespace!=="")for(var b=0,c=namespace.split(".");b<c.length;b++){if(!a)throw Error(c.slice(0,b+1).join(".")+" is not an object");a=a[c[b]]}if(!a||!a.easyXDM)throw Error("Could not find easyXDM in parent."+namespace);return a.easyXDM}
function noConflict(a){if(typeof a!="string"||!a)throw Error("namespace must be a non-empty string");_trace("Settings namespace to '"+a+"'");window.easyXDM=_easyXDM;(namespace=a)&&(IFRAME_PREFIX="easyXDM_"+namespace.replace(".","_")+"_");return easyXDM}function getDomainName(a){if(!a)throw Error("url is undefined or empty");return a.match(reURI)[3]}function getPort(a){if(!a)throw Error("url is undefined or empty");return a.match(reURI)[4]||""}
function getLocation(a){if(!a)throw Error("url is undefined or empty");if(/^file/.test(a))throw Error("The file:// protocol is not supported");var b=a.toLowerCase().match(reURI),a=b[2],c=b[3],b=b[4]||"";if(a=="http:"&&b==":80"||a=="https:"&&b==":443")b="";return a+"//"+c+b}
function resolveUrl(a){if(!a)throw Error("url is undefined or empty");a=a.replace(reDoubleSlash,"$1/");if(!a.match(/^(http||https):\/\//)){var b=a.substring(0,1)==="/"?"":location.pathname;b.substring(b.length-1)!=="/"&&(b=b.substring(0,b.lastIndexOf("/")+1));a=location.protocol+"//"+location.host+b+a}for(;reParent.test(a);)a=a.replace(reParent,"");_trace("resolved url '"+a+"'");return a}
function appendQueryParameters(a,b){if(!b)throw Error("parameters is undefined or null");var c="",d=a.indexOf("#");if(d!==-1){c=a.substring(d);a=a.substring(0,d)}var d=[],e;for(e in b)b.hasOwnProperty(e)&&d.push(e+"="+encodeURIComponent(b[e]));return a+(useHash?"#":a.indexOf("?")==-1?"?":"&")+d.join("&")+c}var query=function(a){for(var a=a.substring(1).split("&"),b={},c,d=a.length;d--;){c=a[d].split("=");b[c[0]]=decodeURIComponent(c[1])}return b}(/xdm_e=/.test(location.search)?location.search:location.hash);
function undef(a){return typeof a==="undefined"}
var getJSON=function(){var a={},b={a:[1,2,3]};if(typeof JSON!="undefined"&&typeof JSON.stringify==="function"&&JSON.stringify(b).replace(/\s/g,"")==='{"a":[1,2,3]}')return JSON;if(Object.toJSON&&Object.toJSON(b).replace(/\s/g,"")==='{"a":[1,2,3]}')a.stringify=Object.toJSON;if(typeof String.prototype.evalJSON==="function"){b='{"a":[1,2,3]}'.evalJSON();if(b.a&&b.a.length===3&&b.a[2]===3)a.parse=function(a){return a.evalJSON()}}if(a.stringify&&a.parse){getJSON=function(){return a};return a}return null};
function apply(a,b,c){var d,e;for(e in b)if(b.hasOwnProperty(e))if(e in a){d=b[e];typeof d==="object"?apply(a[e],d,c):c||(a[e]=b[e])}else a[e]=b[e];return a}function testForNamePropertyBug(){var a=document.body.appendChild(document.createElement("form")),b=a.appendChild(document.createElement("input"));b.name=IFRAME_PREFIX+"TEST"+channelId;HAS_NAME_PROPERTY_BUG=b!==a.elements[b.name];document.body.removeChild(a);_trace("HAS_NAME_PROPERTY_BUG: "+HAS_NAME_PROPERTY_BUG)}
function createFrame(a){_trace("creating frame: "+a.props.src);undef(HAS_NAME_PROPERTY_BUG)&&testForNamePropertyBug();var b;if(HAS_NAME_PROPERTY_BUG)b=document.createElement('<iframe name="'+a.props.name+'"/>');else{b=document.createElement("IFRAME");b.name=a.props.name}b.id=b.name=a.props.name;delete a.props.name;if(typeof a.container=="string")a.container=document.getElementById(a.container);if(!a.container){apply(b.style,{position:"absolute",top:"-2000px",left:"0px"});a.container=document.body}var c=
a.props.src;a.props.src="javascript:false";apply(b,a.props);b.border=b.frameBorder=0;b.allowTransparency=true;a.container.appendChild(b);a.onLoad&&on(b,"load",a.onLoad);b.src=c;a.props.src=c;return b}function checkAcl(a,b){typeof a=="string"&&(a=[a]);for(var c,d=a.length;d--;){c=a[d];c=RegExp(c.substr(0,1)=="^"?c:"^"+c.replace(/(\*)/g,".$1").replace(/\?/g,".")+"$");if(c.test(b))return true}return false}
function prepareTransportStack(a){var b=a.protocol,c;a.isHost=a.isHost||undef(query.xdm_p);useHash=a.hash||false;_trace("preparing transport stack");if(!a.props)a.props={};if(a.isHost){a.remote=resolveUrl(a.remote);a.channel=a.channel||"default"+channelId++;a.secret=Math.random().toString(16).substring(2);if(undef(b)){if(getLocation(location.href)==getLocation(a.remote))b="4";else if(isHostMethod(window,"postMessage")||isHostMethod(document,"postMessage"))b="1";else if(a.swf&&isHostMethod(window,
"ActiveXObject")&&hasFlash())b="6";else if(navigator.product==="Gecko"&&"frameElement"in window&&navigator.userAgent.indexOf("WebKit")==-1)b="5";else if(a.remoteHelper){a.remoteHelper=resolveUrl(a.remoteHelper);b="2"}else b="0";_trace("selecting protocol: "+b)}else _trace("using protocol: "+b)}else{_trace("using parameters from query");a.channel=query.xdm_c.replace(/["'<>\\]/g,"");a.secret=query.xdm_s;a.remote=query.xdm_e.replace(/["'<>\\]/g,"");b=query.xdm_p;if(a.acl&&!checkAcl(a.acl,a.remote))throw Error("Access denied for "+
a.remote);}a.protocol=b;switch(b){case "0":apply(a,{interval:100,delay:2E3,useResize:true,useParent:false,usePolling:false},true);if(a.isHost){if(!a.local){_trace("looking for image to use as local");b=location.protocol+"//"+location.host;c=document.body.getElementsByTagName("img");for(var d,e=c.length;e--;){d=c[e];if(d.src.substring(0,b.length)===b){a.local=d.src;break}}if(!a.local){_trace("no image found, defaulting to using the window");a.local=window}}b={xdm_c:a.channel,xdm_p:0};if(a.local===
window){a.usePolling=true;a.useParent=true;a.local=location.protocol+"//"+location.host+location.pathname+location.search;b.xdm_e=a.local;b.xdm_pa=1}else b.xdm_e=resolveUrl(a.local);if(a.container){a.useResize=false;b.xdm_po=1}a.remote=appendQueryParameters(a.remote,b)}else apply(a,{channel:query.xdm_c,remote:query.xdm_e,useParent:!undef(query.xdm_pa),usePolling:!undef(query.xdm_po),useResize:a.useParent?false:a.useResize});c=[new easyXDM.stack.HashTransport(a),new easyXDM.stack.ReliableBehavior({}),
new easyXDM.stack.QueueBehavior({encode:true,maxLength:4E3-a.remote.length}),new easyXDM.stack.VerifyBehavior({initiate:a.isHost})];break;case "1":c=[new easyXDM.stack.PostMessageTransport(a)];break;case "2":c=[new easyXDM.stack.NameTransport(a),new easyXDM.stack.QueueBehavior,new easyXDM.stack.VerifyBehavior({initiate:a.isHost})];break;case "3":c=[new easyXDM.stack.NixTransport(a)];break;case "4":c=[new easyXDM.stack.SameOriginTransport(a)];break;case "5":c=[new easyXDM.stack.FrameElementTransport(a)];
break;case "6":flashVersion||hasFlash();c=[new easyXDM.stack.FlashTransport(a)]}c.push(new easyXDM.stack.QueueBehavior({lazy:a.lazy,remove:true}));return c}
function chainStack(a){for(var b,c={incoming:function(a,b){this.up.incoming(a,b)},outgoing:function(a,b){this.down.outgoing(a,b)},callback:function(a){this.up.callback(a)},init:function(){this.down.init()},destroy:function(){this.down.destroy()}},d=0,e=a.length;d<e;d++){b=a[d];apply(b,c,true);if(d!==0)b.down=a[d-1];if(d!==e-1)b.up=a[d+1]}return b}function removeFromStack(a){a.up.down=a.down;a.down.up=a.up;a.up=a.down=null}
apply(easyXDM,{version:"%%version%%",query:query,stack:{},apply:apply,getJSONObject:getJSON,whenReady:whenReady,noConflict:noConflict});apply(easyXDM,{checkAcl:checkAcl,getDomainName:getDomainName,getLocation:getLocation,appendQueryParameters:appendQueryParameters});
var debug={_deferred:[],flush:function(){this.trace("... deferred messages ...");for(var a=0,b=this._deferred.length;a<b;a++)this.trace(this._deferred[a]);this._deferred.length=0;this.trace("... end of deferred messages ...")},getTime:function(){var a=new Date,b=a.getHours()+"",c=a.getMinutes()+"",d=a.getSeconds()+"",a=a.getMilliseconds()+"";b.length==1&&(b="0"+b);c.length==1&&(c="0"+c);d.length==1&&(d="0"+d);a="000".substring(a.length)+a;return b+":"+c+":"+d+"."+a},log:function(a){this.log=!isHostObject(window,
"console")||undef(console.log)?emptyFn:function(a){console.log(location.host+(namespace?":"+namespace:"")+" - "+this.getTime()+": "+a)};this.log(a)},trace:function(a){if(domIsReady){var b=document.getElementById("log");if(b)this.trace=function(a){try{b.appendChild(document.createElement("div")).appendChild(document.createTextNode(location.host+(namespace?":"+namespace:"")+" - "+this.getTime()+":"+a));b.scrollTop=b.scrollHeight}catch(c){}};else if(isHostObject(window,"console")&&!undef(console.info))this.trace=
function(a){console.info(location.host+(namespace?":"+namespace:"")+" - "+this.getTime()+":"+a)};else{var c=location.host,d=c.replace(/[\-.:]/g,"")+"easyxdm_log",e;try{e=window.open("",d,"width=800,height=200,status=0,navigation=0,scrollbars=1")}catch(g){}if(e){var f=e.document,b=f.getElementById("log");if(!b){f.write("<html><head><title>easyXDM log "+c+"</title></head>");f.write('<body><div id="log"></div></body></html>');f.close();b=f.getElementById("log")}this.trace=function(a){try{b.appendChild(f.createElement("div")).appendChild(f.createTextNode(location.host+
(namespace?":"+namespace:"")+" - "+this.getTime()+":"+a));b.scrollTop=b.scrollHeight}catch(c){}};this.trace("---- new logger at "+location.href)}if(!b)this.trace=emptyFn}this.trace(a)}else{this._deferred.length===0&&easyXDM.whenReady(debug.flush,debug);this._deferred.push(a);this.log(a)}},getTracer:function(a){return function(b){debug.trace(a+": "+b)}}};debug.log("easyXDM present on '"+location.href);easyXDM.Debug=debug;_trace=debug.getTracer("{Private}");
easyXDM.DomHelper={on:on,un:un,requiresJSON:function(a){if(isHostObject(window,"JSON"))debug.log("native JSON found");else{debug.log("loading external JSON");document.write('<script type="text/javascript" src="'+a+'"><\/script>')}}};(function(){var a={};easyXDM.Fn={set:function(b,c){this._trace("storing function "+b);a[b]=c},get:function(b,c){this._trace("retrieving function "+b);var d=a[b];d||this._trace(b+" not found");c&&delete a[b];return d}};easyXDM.Fn._trace=debug.getTracer("easyXDM.Fn")})();
easyXDM.Socket=function(a){debug.getTracer("easyXDM.Socket")("constructor");var b=chainStack(prepareTransportStack(a).concat([{incoming:function(b,c){a.onMessage(b,c)},callback:function(b){if(a.onReady)a.onReady(b)}}])),c=getLocation(a.remote);this.origin=getLocation(a.remote);this.destroy=function(){b.destroy()};this.postMessage=function(a){b.outgoing(a,c)};b.init()};
easyXDM.Rpc=function(a,b){debug.getTracer("easyXDM.Rpc")("constructor");if(b.local)for(var c in b.local)if(b.local.hasOwnProperty(c)){var d=b.local[c];typeof d==="function"&&(b.local[c]={method:d})}var e=chainStack(prepareTransportStack(a).concat([new easyXDM.stack.RpcBehavior(this,b),{callback:function(b){if(a.onReady)a.onReady(b)}}]));this.origin=getLocation(a.remote);this.destroy=function(){e.destroy()};e.init()};
easyXDM.stack.FlashTransport=function(a){function b(a){setTimeout(function(){d("received message");e.up.incoming(a,f)},0)}function c(b){d("creating factory with SWF from "+b);var c=a.swf+"?host="+a.isHost,e="easyXDM_swf_"+Math.floor(Math.random()*1E4);easyXDM.Fn.set("flash_loaded"+b.replace(/[\-.]/g,"_"),function(){easyXDM.stack.FlashTransport[b].swf=i=h.firstChild;for(var a=easyXDM.stack.FlashTransport[b].queue,c=0;c<a.length;c++)a[c]();a.length=0});if(a.swfContainer)h=typeof a.swfContainer=="string"?
document.getElementById(a.swfContainer):a.swfContainer;else{h=document.createElement("div");apply(h.style,HAS_FLASH_THROTTLED_BUG&&a.swfNoThrottle?{height:"20px",width:"20px",position:"fixed",right:0,top:0}:{height:"1px",width:"1px",position:"absolute",overflow:"hidden",right:0,top:0});document.body.appendChild(h)}var f="callback=flash_loaded"+b.replace(/[\-.]/g,"_")+"&proto="+global.location.protocol+"&domain="+getDomainName(global.location.href)+"&port="+getPort(global.location.href)+"&ns="+namespace,
f=f+"&log=true";h.innerHTML="<object height='20' width='20' type='application/x-shockwave-flash' id='"+e+"' data='"+c+"'><param name='allowScriptAccess' value='always'></param><param name='wmode' value='transparent'><param name='movie' value='"+c+"'></param><param name='flashvars' value='"+f+"'></param><embed type='application/x-shockwave-flash' FlashVars='"+f+"' allowScriptAccess='always' wmode='transparent' src='"+c+"' height='1' width='1'></embed></object>"}var d=debug.getTracer("easyXDM.stack.FlashTransport");
d("constructor");if(!a.swf)throw Error("Path to easyxdm.swf is missing");var e,g,f,i,h;return e={outgoing:function(b,c,d){i.postMessage(a.channel,b.toString());d&&d()},destroy:function(){d("destroy");try{i.destroyChannel(a.channel)}catch(b){}i=null;if(g){g.parentNode.removeChild(g);g=null}},onDOMReady:function(){d("init");f=a.remote;easyXDM.Fn.set("flash_"+a.channel+"_init",function(){setTimeout(function(){d("firing onReady");e.up.callback(true)})});easyXDM.Fn.set("flash_"+a.channel+"_onMessage",
b);a.swf=resolveUrl(a.swf);var h=getDomainName(a.swf),k=function(){easyXDM.stack.FlashTransport[h].init=true;i=easyXDM.stack.FlashTransport[h].swf;i.createChannel(a.channel,a.secret,getLocation(a.remote),a.isHost);if(a.isHost){HAS_FLASH_THROTTLED_BUG&&a.swfNoThrottle&&apply(a.props,{position:"fixed",right:0,top:0,height:"20px",width:"20px"});apply(a.props,{src:appendQueryParameters(a.remote,{xdm_e:getLocation(location.href),xdm_c:a.channel,xdm_p:6,xdm_s:a.secret}),name:IFRAME_PREFIX+a.channel+"_provider"});
g=createFrame(a)}};if(easyXDM.stack.FlashTransport[h]&&easyXDM.stack.FlashTransport[h].init)k();else if(easyXDM.stack.FlashTransport[h])easyXDM.stack.FlashTransport[h].queue.push(k);else{easyXDM.stack.FlashTransport[h]={queue:[k]};c(h)}},init:function(){whenReady(e.onDOMReady,e)}}};
easyXDM.stack.SameOriginTransport=function(a){var b=debug.getTracer("easyXDM.stack.SameOriginTransport");b("constructor");var c,d,e,g;return c={outgoing:function(a,b,c){e(a);c&&c()},destroy:function(){b("destroy");if(d){d.parentNode.removeChild(d);d=null}},onDOMReady:function(){b("init");g=getLocation(a.remote);if(a.isHost){apply(a.props,{src:appendQueryParameters(a.remote,{xdm_e:location.protocol+"//"+location.host+location.pathname,xdm_c:a.channel,xdm_p:4}),name:IFRAME_PREFIX+a.channel+"_provider"});
d=createFrame(a);easyXDM.Fn.set(a.channel,function(a){e=a;setTimeout(function(){c.up.callback(true)},0);return function(a){c.up.incoming(a,g)}})}else{e=getParentObject().Fn.get(a.channel,true)(function(a){c.up.incoming(a,g)});setTimeout(function(){c.up.callback(true)},0)}},init:function(){whenReady(c.onDOMReady,c)}}};
easyXDM.stack.PostMessageTransport=function(a){function b(b){var e;if(b.origin)e=getLocation(b.origin);else if(b.uri)e=getLocation(b.uri);else if(b.domain)e=location.protocol+"//"+b.domain;else throw"Unable to retrieve the origin of the event";c("received message '"+b.data+"' from "+e);e==f&&b.data.substring(0,a.channel.length+1)==a.channel+" "&&d.up.incoming(b.data.substring(a.channel.length+1),e)}var c=debug.getTracer("easyXDM.stack.PostMessageTransport");c("constructor");var d,e,g,f;return d={outgoing:function(b,
c,d){g.postMessage(a.channel+" "+b,c||f);d&&d()},destroy:function(){c("destroy");un(window,"message",b);if(e){g=null;e.parentNode.removeChild(e);e=null}},onDOMReady:function(){c("init");f=getLocation(a.remote);if(a.isHost){var i=function(f){if(f.data==a.channel+"-ready"){c("firing onReady");g="postMessage"in e.contentWindow?e.contentWindow:e.contentWindow.document;un(window,"message",i);on(window,"message",b);setTimeout(function(){d.up.callback(true)},0)}};on(window,"message",i);apply(a.props,{src:appendQueryParameters(a.remote,
{xdm_e:getLocation(location.href),xdm_c:a.channel,xdm_p:1}),name:IFRAME_PREFIX+a.channel+"_provider"});e=createFrame(a)}else{on(window,"message",b);g="postMessage"in window.parent?window.parent:window.parent.document;g.postMessage(a.channel+"-ready",f);setTimeout(function(){d.up.callback(true)},0)}},init:function(){whenReady(d.onDOMReady,d)}}};
easyXDM.stack.FrameElementTransport=function(a){var b=debug.getTracer("easyXDM.stack.FrameElementTransport");b("constructor");var c,d,e,g;return c={outgoing:function(a,b,c){e.call(this,a);c&&c()},destroy:function(){b("destroy");if(d){d.parentNode.removeChild(d);d=null}},onDOMReady:function(){b("init");g=getLocation(a.remote);if(a.isHost){apply(a.props,{src:appendQueryParameters(a.remote,{xdm_e:getLocation(location.href),xdm_c:a.channel,xdm_p:5}),name:IFRAME_PREFIX+a.channel+"_provider"});d=createFrame(a);
d.fn=function(a){delete d.fn;e=a;setTimeout(function(){c.up.callback(true)},0);return function(a){c.up.incoming(a,g)}}}else{if(document.referrer&&getLocation(document.referrer)!=query.xdm_e)window.top.location=query.xdm_e;e=window.frameElement.fn(function(a){c.up.incoming(a,g)});c.up.callback(true)}},init:function(){whenReady(c.onDOMReady,c)}}};
easyXDM.stack.NameTransport=function(a){function b(b){var c=a.remoteHelper+(i?"#_3":"#_2")+a.channel;g("sending message "+b);g("navigating to  '"+c+"'");h.contentWindow.sendMessage(b,c)}function c(){if(i)(++k===2||!i)&&f.up.callback(true);else{b("ready");g("calling onReady");f.up.callback(true)}}function d(a){g("received message "+a);f.up.incoming(a,m)}function e(){l&&setTimeout(function(){l(true)},0)}var g=debug.getTracer("easyXDM.stack.NameTransport");g("constructor");if(a.isHost&&undef(a.remoteHelper)){g("missing remoteHelper");
throw Error("missing remoteHelper");}var f,i,h,j,k,l,m,n;return f={outgoing:function(a,c,d){l=d;b(a)},destroy:function(){g("destroy");h.parentNode.removeChild(h);h=null;if(i){j.parentNode.removeChild(j);j=null}},onDOMReady:function(){g("init");i=a.isHost;k=0;m=getLocation(a.remote);a.local=resolveUrl(a.local);if(i){easyXDM.Fn.set(a.channel,function(b){g("received initial message "+b);if(i&&b==="ready"){easyXDM.Fn.set(a.channel,d);c()}});n=appendQueryParameters(a.remote,{xdm_e:a.local,xdm_c:a.channel,
xdm_p:2});apply(a.props,{src:n+"#"+a.channel,name:IFRAME_PREFIX+a.channel+"_provider"});j=createFrame(a)}else{a.remoteHelper=a.remote;easyXDM.Fn.set(a.channel,d)}var b=function(){var d=h||this;un(d,"load",b);easyXDM.Fn.set(a.channel+"_load",e);(function q(){typeof d.contentWindow.sendMessage=="function"?c():setTimeout(q,50)})()};h=createFrame({props:{src:a.local+"#_4"+a.channel},onLoad:b})},init:function(){whenReady(f.onDOMReady,f)}}};
easyXDM.stack.HashTransport=function(a){function b(){if(k){var a=k.location.href,b="",c=a.indexOf("#");c!=-1&&(b=a.substring(c));if(b&&b!=h){d("poll: new message");h=b;d("received message '"+h+"' from "+n);e.up.incoming(h.substring(h.indexOf("_")+1),n)}}}function c(){d("starting polling");f=setInterval(b,i)}var d=debug.getTracer("easyXDM.stack.HashTransport");d("constructor");var e,g,f,i,h,j,k,l,m,n;return e={outgoing:function(b){d("sending message '"+(j+1)+" "+b+"' to "+n);if(l){b=a.remote+"#"+j++ +
"_"+b;(g||!m?l.contentWindow:l).location=b}else d("no caller window")},destroy:function(){window.clearInterval(f);(g||!m)&&l.parentNode.removeChild(l);l=null},onDOMReady:function(){g=a.isHost;i=a.interval;h="#"+a.channel;j=0;m=a.useParent;n=getLocation(a.remote);if(g){apply(a.props,{src:a.remote,name:IFRAME_PREFIX+a.channel+"_provider"});if(m)a.onLoad=function(){k=window;c();e.up.callback(true)};else{var b=0,f=a.delay/50;(function q(){if(++b>f){d("unable to get reference to _listenerWindow, giving up");
throw Error("Unable to reference listenerwindow");}try{k=l.contentWindow.frames[IFRAME_PREFIX+a.channel+"_consumer"]}catch(g){}if(k){c();d("got a reference to _listenerWindow");e.up.callback(true)}else setTimeout(q,50)})()}l=createFrame(a)}else{k=window;c();if(m){l=parent;e.up.callback(true)}else{apply(a,{props:{src:a.remote+"#"+a.channel+new Date,name:IFRAME_PREFIX+a.channel+"_consumer"},onLoad:function(){e.up.callback(true)}});l=createFrame(a)}}},init:function(){whenReady(e.onDOMReady,e)}}};
easyXDM.stack.ReliableBehavior=function(){var a=debug.getTracer("easyXDM.stack.ReliableBehavior");a("constructor");var b,c,d=0,e=0,g="";return b={incoming:function(f,i){a("incoming: "+f);var h=f.indexOf("_"),j=f.substring(0,h).split(","),f=f.substring(h+1);if(j[0]==d){a("message delivered");g="";c&&c(true)}if(f.length>0){a("sending ack, and passing on "+f);b.down.outgoing(j[1]+","+d+"_"+g,i);if(e!=j[1]){e=j[1];b.up.incoming(f,i)}}},outgoing:function(a,i,h){g=a;c=h;b.down.outgoing(e+","+ ++d+"_"+a,
i)}}};
easyXDM.stack.QueueBehavior=function(a){function b(){if(a.remove&&e.length===0){c("removing myself from the stack");removeFromStack(d)}else if(!g&&!(e.length===0||i)){c("dispatching from queue");g=true;var f=e.shift();d.down.outgoing(f.data,f.origin,function(a){g=false;f.callback&&setTimeout(function(){f.callback(a)},0);b()})}}var c=debug.getTracer("easyXDM.stack.QueueBehavior");c("constructor");var d,e=[],g=true,f="",i,h=0,j=false,k=false;return d={init:function(){undef(a)&&(a={});if(a.maxLength){h=a.maxLength;
k=true}a.lazy?j=true:d.down.init()},callback:function(a){g=false;var c=d.up;b();c.callback(a)},incoming:function(b,e){if(k){var g=b.indexOf("_"),h=parseInt(b.substring(0,g),10);f=f+b.substring(g+1);if(h===0){c("received the last fragment");a.encode&&(f=decodeURIComponent(f));d.up.incoming(f,e);f=""}else c("waiting for more fragments, seq="+b)}else d.up.incoming(b,e)},outgoing:function(f,g,i){a.encode&&(f=encodeURIComponent(f));var p=[],o;if(k){for(;f.length!==0;){o=f.substring(0,h);f=f.substring(o.length);
p.push(o)}for(;o=p.shift();){c("enqueuing");e.push({data:p.length+"_"+o,origin:g,callback:p.length===0?i:null})}}else e.push({data:f,origin:g,callback:i});j?d.down.init():b()},destroy:function(){c("destroy");i=true;d.down.destroy()}}};
easyXDM.stack.VerifyBehavior=function(a){function b(){c("requesting verification");e=Math.random().toString(16).substring(2);d.down.outgoing(e)}var c=debug.getTracer("easyXDM.stack.VerifyBehavior");c("constructor");if(undef(a.initiate))throw Error("settings.initiate is not set");var d,e,g;return d={incoming:function(f,i){var h=f.indexOf("_");if(h===-1)if(f===e){c("verified, calling callback");d.up.callback(true)}else{if(!g){c("returning secret");g=f;a.initiate||b();d.down.outgoing(f)}}else f.substring(0,
h)===g&&d.up.incoming(f.substring(h+1),i)},outgoing:function(a,b,c){d.down.outgoing(e+"_"+a,b,c)},callback:function(){a.initiate&&b()}}};
easyXDM.stack.RpcBehavior=function(a,b){function c(a){a.jsonrpc="2.0";f.down.outgoing(i.stringify(a))}function d(a,b){var d=Array.prototype.slice;g("creating method "+b);return function(){g("executing method "+b);var e=arguments.length,f,i={method:b};if(e>0&&typeof arguments[e-1]==="function"){if(e>1&&typeof arguments[e-2]==="function"){f={success:arguments[e-2],error:arguments[e-1]};i.params=d.call(arguments,0,e-2)}else{f={success:arguments[e-1]};i.params=d.call(arguments,0,e-1)}j[""+ ++h]=f;i.id=
h}else i.params=d.call(arguments,0);if(a.namedParams&&i.params.length===1)i.params=i.params[0];c(i)}}function e(a,b,d,e){if(d){g("requested to execute procedure "+a);var f,h;if(b){f=function(a){f=emptyFn;c({id:b,result:a})};h=function(a,d){h=emptyFn;var e={id:b,error:{code:-32099,message:a}};if(d)e.error.data=d;c(e)}}else f=h=emptyFn;isArray(e)||(e=[e]);try{var i=d.method.apply(d.scope,e.concat([f,h]));undef(i)||f(i)}catch(j){h(j.message)}}else{g("requested to execute non-existent procedure "+a);
b&&c({id:b,error:{code:-32601,message:"Procedure not found."}})}}var g=debug.getTracer("easyXDM.stack.RpcBehavior"),f,i=b.serializer||getJSON(),h=0,j={};return f={incoming:function(a){a=i.parse(a);if(a.method){g("received request to execute method "+a.method+(a.id?" using callback id "+a.id:""));b.handle?b.handle(a,c):e(a.method,a.id,b.local[a.method],a.params)}else{g("received return value destined to callback with id "+a.id);var d=j[a.id];a.error?d.error?d.error(a.error):g("unhandled error returned."):
d.success&&d.success(a.result);delete j[a.id]}},init:function(){g("init");if(b.remote){g("creating stubs");for(var c in b.remote)b.remote.hasOwnProperty(c)&&(a[c]=d(b.remote[c],c))}f.down.init()},destroy:function(){g("destroy");for(var c in b.remote)b.remote.hasOwnProperty(c)&&a.hasOwnProperty(c)&&delete a[c];f.down.destroy()}}};